export JDK_8=/home/denghg/tools/jdk-11.0.22
export JDK_17=/usr/lib/jvm/jdk-17.0.11
export JAVA_HOME=$JDK_17
export JRE_HOME=$JAVA_HOME/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export ANDROID_NDK=/home/denghg/Android/android-ndk-r15c
#export ANDROID_NDK=/home/denghg/Android/android-ndk-r21e
export ANDROID_HOME=/home/denghg/Android/Sdk
export ANDROID_SDK=/home/denghg/Android/Sdk
export CMAKE_PATH=/home/denghg/Android/Sdk/cmake/3.10.2.4988404/bin
export DEPOT_TOOL=/home/denghg/sourceCode/huaweiyun_sourceAndroidWebrtc/android_webrtc/depot_tools
export NODE_PATH=/usr/local/node/bin
export GOROOT=/usr/local/go/bin
export GOPATH=/home/denghg/goWorkspace   
export NGINX=/usr/local/nginx/sbin
export GOPROXY=https://goproxy.cn
export FFMPEG_PATH=/usr/local/ffmpeg/bin
export SVG_PATH=/home/denghg/tools/tool/SVG-Android/svg-vector-cli/bat
export SHELL_PATH=/usr/local/shell
export FLUTTER_PATH=/home/denghg/Flutter/flutter/bin
export FLUTTER324_PATH=/home/denghg/Flutter/flutter3.24.5/flutter/bin
export PATH=$FLUTTER324_PATH:$PATH:$JAVA_HOME:$ANDROID_NDK:$ANDROID_SDK:$ANDROID_HOME:$CMAKE_PATH:$DEPOT_TOOL:$NODE_PATH:$GOROOT:$GOPATH:$NGINX:$GOPROXY:$FFMPEG_PATH:$SVG_PATH:$SHELL_PATH
export NC_PATH=/home/denghg/github/nextcloudclient/voicevision_res/src/main/res/drawable
alias addrPath="cd /home/denghg/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin"
alias addr2linecli="./llvm-addr2line -f -e /home/denghg/github/nextcloudclient/rtc_framework/src/main/jniLibs/arm64-v8a/libjingle_peerconnection_so.so"
alias svgcli="java -jar /home/denghg/tools/tool/SVG-Android/svg-vector-cli/bat/svg2vector-cli-1.0.1.jar"
alias drawablecli="cd /home/denghg/tools/tool && ./svg_drawable.sh"
alias killwxwork="sudo kill -9 $(pidof WXWork.exe)"
alias reinstallwxwork="cd /home/denghg/tools &&  sudo dpkg -i ukylin-wxwork_1.0_amd64.deb" 
alias removewxwork="cd /home/denghg/tools && sudo apt-get remove ukylin-wxwork"
alias killwechat="sudo kill -9 $(pidof WeChat.exe)"
alias killnode="sudo kill -9 $(pidof node)"
alias mkbuild="mkdir build && cd ./build"
alias mkmk="cmake .. && make"
alias findmanifest="find . -name AndroidManifest.xml"
alias findgradle="find . -name build.gradle"
export killwxworkpath="sudo kill -9 $(pidof WXWork.exe)"
export killnodepath="sudo kill -9 $(pidof node)"
alias runtime="adb logcat | grep AndroidRuntime"
alias webrtcdir="cd /home/denghg/sourceCode/android_webrtc/src"
alias srtijk="cd /home/denghg/workspace/srt_work/ijkplayer"
alias gits="git status"
alias gd="git diff"
alias gl="git log"
alias srtrelease="cd /home/denghg/workspace/srt_ijkplayer_source/srt/ijkplayer"
alias startstudio=" ./Android/android-studio/bin/studio.sh "
alias wxwork="cd /home/denghg/.ukylin-wine/wxwork/drive_c/users/denghg/Application\ Data/Tencent/WXWork/Data/1688855458439847/Cache/File/2023-06"
. "$HOME/.cargo/env
"
